# This is a basic workflow to help you get started with Actions

name: Daily Report

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron: '0 22 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Time to scraper!
        run: |
          curl --request GET \
          --url 'https://aricasas.vercel.app/api/scraper' \
          --header '${{ secrets.HEADER_ARICAN_KEY }}: ${{ secrets.HEADER_ARICAN_TOKEN }}'
